In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline 
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split,GridSearchCV,StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,ConfusionMatrixDisplay

In [3]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/_0eYOqji3unP1tDNKWZMjg/weatherAUS-2.csv"
df = pd.read_csv(url)
df.head()

         Date Location  MinTemp  ...  Temp3pm  RainToday  RainTomorrow
0  2008-12-01   Albury     13.4  ...     21.8         No            No
1  2008-12-02   Albury      7.4  ...     24.3         No            No
2  2008-12-03   Albury     12.9  ...     23.2         No            No
3  2008-12-04   Albury      9.2  ...     26.5         No            No
4  2008-12-05   Albury     17.5  ...     29.7         No            No

[5 rows x 23 columns]

In [4]:
df.count()

Date             145460
Location         145460
MinTemp          143975
MaxTemp          144199
Rainfall         142199
Evaporation       82670
Sunshine          75625
WindGustDir      135134
WindGustSpeed    135197
WindDir9am       134894
WindDir3pm       141232
WindSpeed9am     143693
WindSpeed3pm     142398
Humidity9am      142806
Humidity3pm      140953
Pressure9am      130395
Pressure3pm      130432
Cloud9am          89572
Cloud3pm          86102
Temp9am          143693
Temp3pm          141851
RainToday        142199
RainTomorrow     142193
dtype: int64

In [7]:
df = df.dropna()
df.info()

<class 'pandas.DataFrame'>
Index: 56420 entries, 6049 to 142302
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           56420 non-null  str
 1   Location       56420 non-null  str
 2   MinTemp        56420 non-null  float64
 3   MaxTemp        56420 non-null  float64
 4   Rainfall       56420 non-null  float64
 5   Evaporation    56420 non-null  float64
 6   Sunshine       56420 non-null  float64
 7   WindGustDir    56420 non-null  str
 8   WindGustSpeed  56420 non-null  float64
 9   WindDir9am     56420 non-null  str
 10  WindDir3pm     56420 non-null  str
 11  WindSpeed9am   56420 non-null  float64
 12  WindSpeed3pm   56420 non-null  float64
 13  Humidity9am    56420 non-null  float64
 14  Humidity3pm    56420 non-null  float64
 15  Pressure9am    56420 non-null  float64
 16  Pressure3pm    56420 non-null  float64
 17  Cloud9am       56420 non-null  float64
 18  Cloud3pm       56420 non-null  float64
 19  Temp9am        56420 non-null  float64
 20  Temp3pm        56420 non-null  float64
 21  RainToday      56420 non-null  str
 22  RainTomorrow   56420 non-null  str
dtypes: float64(16), str(7)
memory usage: 12.0 MB

In [8]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='str')

In [10]:
df = df.rename(columns={'RainToday': 'RainYesterday',
                        'RainTomorrow': 'RainToday'
                        })

In [11]:
df = df[df.Location.isin(['Melbourne','MelbourneAirport','Watsonia',])]
df. info()

<class 'pandas.DataFrame'>
Index: 7557 entries, 64191 to 80997
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           7557 non-null   str
 1   Location       7557 non-null   str
 2   MinTemp        7557 non-null   float64
 3   MaxTemp        7557 non-null   float64
 4   Rainfall       7557 non-null   float64
 5   Evaporation    7557 non-null   float64
 6   Sunshine       7557 non-null   float64
 7   WindGustDir    7557 non-null   str
 8   WindGustSpeed  7557 non-null   float64
 9   WindDir9am     7557 non-null   str
 10  WindDir3pm     7557 non-null   str
 11  WindSpeed9am   7557 non-null   float64
 12  WindSpeed3pm   7557 non-null   float64
 13  Humidity9am    7557 non-null   float64
 14  Humidity3pm    7557 non-null   float64
 15  Pressure9am    7557 non-null   float64
 16  Pressure3pm    7557 non-null   float64
 17  Cloud9am       7557 non-null   float64
 18  Cloud3pm       7557 non-null   float64
 19  Temp9am        7557 non-null   float64
 20  Temp3pm        7557 non-null   float64
 21  RainYesterday  7557 non-null   str
 22  RainToday      7557 non-null   str
dtypes: float64(16), str(7)
memory usage: 1.6 MB

In [24]:
def date_to_season(date):
    month = date.month
    if (month == 12) or (month == 1) or (month == 2):
        return 'Summer'
    elif (month == 3) or (month == 4) or (month == 5):
        return 'Autumn'
    elif (month == 6) or (month == 7) or (month == 8):
        return 'Winter'
    elif (month == 9) or (month == 10) or (month == 11):
        return 'Spring'

In [27]:
df['Date'] = pd.to_datetime(df['Date'])

# Apply the function to the 'Date' column
df['Season'] = df['Date'].apply(date_to_season)

df=df.drop(columns='Date')
df

               Location  MinTemp  MaxTemp  ...  RainToday       Data  Season
64191  MelbourneAirport     11.2     19.9  ...        Yes 2009-01-01  Summer
64192  MelbourneAirport      7.8     17.8  ...         No 2009-01-02  Summer
64193  MelbourneAirport      6.3     21.1  ...         No 2009-01-03  Summer
64194  MelbourneAirport      8.1     29.2  ...         No 2009-01-04  Summer
64195  MelbourneAirport      9.7     29.0  ...         No 2009-01-05  Summer
...                 ...      ...      ...  ...        ...        ...     ...
80992          Watsonia      3.6     14.5  ...         No 2017-06-20  Winter
80994          Watsonia      4.8     13.3  ...         No 2017-06-22  Winter
80995          Watsonia      5.6     13.1  ...        Yes 2017-06-23  Winter
80996          Watsonia      6.9     12.1  ...         No 2017-06-24  Winter
80997          Watsonia      7.9     13.0  ...         No 2017-06-25  Winter

[7557 rows x 24 columns]

In [29]:
X = df.drop(columns = 'Season')
y = df['Season']

In [30]:
y.value_counts()

Season
Autumn    1947
Winter    1918
Spring    1911
Summer    1781
Name: count, dtype: int64

In [31]:
df['Rainfall'].value_counts()

Rainfall
0.0     4452
0.2      550
0.4      258
0.6      198
0.8      157
        ...
32.8       1
31.4       1
25.8       1
24.4       1
13.0       1
Name: count, Length: 172, dtype: int64

In [32]:
df['Rainfall'].value_counts(normalize = True)*100

Rainfall
0.0     58.912267
0.2      7.278020
0.4      3.414053
0.6      2.620087
0.8      2.077544
          ...
32.8     0.013233
31.4     0.013233
25.8     0.013233
24.4     0.013233
13.0     0.013233
Name: proportion, Length: 172, dtype: float64

In [35]:
# Write your response.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [36]:
numeric_features = X_train.select_dtypes(include=['number']).columns.tolist()  
categorical_features = X_train.select_dtypes(include=['object', 'category']).columns.tolist()

C:\Users\divya\AppData\Local\Temp\ipykernel_16904\1005800964.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_train.select_dtypes(include=['object', 'category']).columns.tolist()

In [37]:
numeric_transformer = Pipeline(steps = [('scaler',StandardScaler)])

categorical_transformer = Pipeline(steps = [('onehot',OneHotEncoder(handle_unknown = 'ignore'))])