In [13]:
import chart_studio.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
import plotly.graph_objs as go
# !pip install chart-studio

In [14]:
init_notebook_mode(connected = True)

In [19]:
data = dict(type = 'choropleth',locations = ['AZ','CA','NY'],locationmode = 'USA-states',colorscale = 'Portland',text = ['text 1','text 2','text 3'],z = [1.0,2.0,3.0],colorbar = {'title':'Colorbar Title Goes Here'})

In [20]:
layout = dict(geo = {'scope':'usa'})

In [21]:
choromap = go.Figure(data = [data],layout = layout)

In [22]:
iplot(choromap)

In [25]:
import pandas as pd
df = pd.read_csv('2011_us_agri_Exports')

In [26]:
df.head()

,code,state,category,total exports,beef,pork,poultry,dairy,fruits fresh,fruits proc,total fruits,veggies fresh,veggies proc,total veggies,corn,wheat,cotton,text
0,AL,Alabama,state,1390.63,34.4,10.6,481.0,4.06,8.0,17.1,25.11,5.5,8.9,14.33,34.9,70.0,317.61,Alabama<br>Beef 34.4 Dairy 4.06<br>Fruits 25.1...
1,AK,Alaska,state,13.31,0.2,0.1,0.0,0.19,0.0,0.0,0.00,0.6,1.0,1.56,0.0,0.0,0.00,Alaska<br>Beef 0.2 Dairy 0.19<br>Fruits 0.0 Ve...
2,AZ,Arizona,state,1463.17,71.3,17.9,0.0,105.48,19.3,41.0,60.27,147.5,239.4,386.91,7.3,48.7,423.95,Arizona<br>Beef 71.3 Dairy 105.48<br>Fruits 60...
3,AR,Arkansas,state,3586.02,53.2,29.4,562.9,3.53,2.2,4.7,6.88,4.4,7.1,11.45,69.5,114.5,665.44,Arkansas<br>Beef 53.2 Dairy 3.53<br>Fruits 6.8...
4,CA,California,state,16472.88,228.7,11.1,225.4,929.95,2791.8,5944.6,8736.40,803.2,1303.5,2106.79,34.6,249.3,1064.95,California<br>Beef 228.7 Dairy 929.95<br>Frui...

In [36]:
data = dict(type = 'choropleth',
              colorscale='YlOrRd',
              locations = df['code'],
              locationmode = 'USA-states',
              z = df['total exports'],
              text = df['text'],
              marker = dict(line = dict(color = 'rgb(255,255,255)',width =2)),
              colorbar = {'title':'Millions USD'})

In [37]:
layout = dict(title = '2011 US Agricultute Exports By Sates',geo = dict(scope = 'usa',showlakes = True,lakecolor = 'rgb(85,173,240)'))

In [38]:
layout

{'title': '2011 US Agricultute Exports By Sates',
 'geo': {'scope': 'usa', 'showlakes': True, 'lakecolor': 'rgb(85,173,240)'}}

In [39]:
choromap2 = go.Figure(data = [data],layout = layout)

In [40]:
iplot(choromap2)

In [42]:
df = pd.read_csv('2014_World_GDP')

In [43]:
df.head()

          COUNTRY  GDP (BILLIONS) CODE
0     Afghanistan           21.71  AFG
1         Albania           13.40  ALB
2         Algeria          227.80  DZA
3  American Samoa            0.75  ASM
4         Andorra            4.80  AND

In [46]:
data = dict(type = 'choropleth',
            locations = df['CODE'],
            z = df['GDP (BILLIONS)'],
            text = df['COUNTRY'],
            colorbar = {'title':'GDP in Billions USD'})

In [47]:
layout = dict(title = '2014 Global GDP',
                geo = dict(showframe = False,
                projection = {'type':'Mercator'}))

In [49]:
choromap3 = go.Figure(data = [data],layout = layout)

ValueError:
    Invalid value of type 'builtins.str' received for the 'type' property of layout.geo.projection
        Received value: 'Mercator'

    The 'type' property is an enumeration that may be specified as:
      - One of the following enumeration values:
            ['airy', 'aitoff', 'albers', 'albers usa', 'august',
            'azimuthal equal area', 'azimuthal equidistant', 'baker',
            'bertin1953', 'boggs', 'bonne', 'bottomley', 'bromley',
            'collignon', 'conic conformal', 'conic equal area', 'conic
            equidistant', 'craig', 'craster', 'cylindrical equal
            area', 'cylindrical stereographic', 'eckert1', 'eckert2',
            'eckert3', 'eckert4', 'eckert5', 'eckert6', 'eisenlohr',
            'equal earth', 'equirectangular', 'fahey', 'foucaut',
            'foucaut sinusoidal', 'ginzburg4', 'ginzburg5',
            'ginzburg6', 'ginzburg8', 'ginzburg9', 'gnomonic',
            'gringorten', 'gringorten quincuncial', 'guyou', 'hammer',
            'hill', 'homolosine', 'hufnagel', 'hyperelliptical',
            'kavrayskiy7', 'lagrange', 'larrivee', 'laskowski',
            'loximuthal', 'mercator', 'miller', 'mollweide', 'mt flat
            polar parabolic', 'mt flat polar quartic', 'mt flat polar
            sinusoidal', 'natural earth', 'natural earth1', 'natural
            earth2', 'nell hammer', 'nicolosi', 'orthographic',
            'patterson', 'peirce quincuncial', 'polyconic',
            'rectangular polyconic', 'robinson', 'satellite', 'sinu
            mollweide', 'sinusoidal', 'stereographic', 'times',
            'transverse mercator', 'van der grinten', 'van der
            grinten2', 'van der grinten3', 'van der grinten4',
            'wagner4', 'wagner6', 'wiechel', 'winkel tripel',
            'winkel3']